spring.application.name=quadro-a-quadro

#configuração h2
spring.datasource.url=jdbc:h2:mem:quadrodb
#jdbc é o protocolo de conexão java com o banco
#h2:mem é porque está rodando na memória ram
spring.datasource.driver-class-name=org.h2.Driver
#drive do h2 está sendo usado
spring.datasource.username=admin
spring.datasource.password=123

#console h2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#JPA
#jpa precisa de um dialeto pra funcionar, nesse caso é o H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
#spring mostra no terminal todos o sql que o jpa gerar
spring.jpa.show-sql=true

#porta do servidor
server.port=8080